KER-320 : Job definition not updated after changed in configuration
exoplatform/kernel pull request #47
Opened 2016-10-20 12:27 UTC by aboughzela

Update persisted job data 
* Updated jobDetail after changed in configuration
* Remove job if the same job key (jobName, JobGroup) is removed from configuration

2016-10-20 13:47 UTC, thomasdelhomenie requested changes

2016-10-20 13:47 UTC, thomasdelhomenie commented on exo.kernel.component.common/src/main/java/org/exoplatform/services/scheduler/impl/JobSchedulerServiceImpl.java
> +            scheduler_.deleteJob(jobKey);
Do you remove all jobs at each startup here ?

2016-10-20 13:47 UTC, thomasdelhomenie commented on exo.kernel.component.common/src/main/java/org/exoplatform/services/scheduler/impl/JobSchedulerServiceImpl.java
> +   private void getAllJobKey() {
We should either rename it to "loadAllJobKeys", or to make it return the list of job keys. It is weird to have a get which returns nothing.

2016-10-20 13:47 UTC, thomasdelhomenie commented on exo.kernel.component.common/src/main/java/org/exoplatform/services/scheduler/impl/JobSchedulerServiceImpl.java
> +         List<String> jgroups = scheduler_.getJobGroupNames();
The name is quite confusing :) We should rename it to jobGroupNames instead IMO.

2016-10-20 13:47 UTC, thomasdelhomenie commented on exo.kernel.component.common/src/main/java/org/exoplatform/services/scheduler/impl/JobSchedulerServiceImpl.java
> +            scheduler_.deleteJob(jobKey);
You could use deleteJobs(persistedJobKeyList) instead.

2016-10-20 13:47 UTC, thomasdelhomenie commented on exo.kernel.component.common/src/main/java/org/exoplatform/services/scheduler/impl/JobSchedulerServiceImpl.java
> +      }else{
else is useless here

2016-10-20 13:58 UTC, thomasdelhomenie requested changes
Unit tests are missing.

2016-10-21 08:16 UTC, aboughzela commented on exo.kernel.component.common/src/main/java/org/exoplatform/services/scheduler/impl/JobSchedulerServiceImpl.java
> +            scheduler_.deleteJob(jobKey);
No, at start JobSchedulerServiceImpl service , I remove only the list of old  persisted jobs removed from the configuration (persistedJobKeyList contain at start point only the diff between configuration and old persisted list).

2016-10-21 08:19 UTC, aboughzela commented on exo.kernel.component.common/src/main/java/org/exoplatform/services/scheduler/impl/JobSchedulerServiceImpl.java
> +            scheduler_.deleteJob(jobKey);
you need to refactoring this code ?

2016-10-21 08:42 UTC, aboughzela commented on exo.kernel.component.common/src/main/java/org/exoplatform/services/scheduler/impl/JobSchedulerServiceImpl.java
> +   private void getAllJobKey() {
Done

2016-10-21 08:42 UTC, aboughzela commented on exo.kernel.component.common/src/main/java/org/exoplatform/services/scheduler/impl/JobSchedulerServiceImpl.java
> +         List<String> jgroups = scheduler_.getJobGroupNames();
Done

2016-10-21 08:42 UTC, aboughzela commented on exo.kernel.component.common/src/main/java/org/exoplatform/services/scheduler/impl/JobSchedulerServiceImpl.java
> +      }else{
Done

2016-10-21 08:50 UTC, aboughzela commented
>> Unit tests are missing. 
The PR  fix a specific scenario , reproduced only with job Stored Persistence before start the standalone container.

2016-10-24 09:05 UTC, aboughzela commented
@thomasdelhomenie PR updated
Use scheduler_.rescheduleJob to update only cron job expression or Period Job period time without remove the job

2016-10-24 12:44 UTC, thomasdelhomenie approved these changes

2016-10-24 19:31 UTC, closed without merging